import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { DashboardResponse, RiskResponse } from "./types";

export function generateReport(
  dashboard: DashboardResponse,
  risk: RiskResponse | null
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const now = new Date().toLocaleString();

  // ---- Header ----
  doc.setFillColor(21, 38, 104); // brand navy
  doc.rect(0, 0, pageWidth, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("CivicLens AI — Risk Report", 14, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Dataset: ${dashboard.filename}  |  Generated: ${now}`, 14, 21);

  // ---- Summary KPIs ----
  const s = dashboard.summary;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, 40);

  autoTable(doc, {
    startY: 44,
    head: [["Total Complaints", "High-Risk Wards", "Resolved", "Pending"]],
    body: [
      [
        String(s.total_complaints),
        String(s.high_risk_wards),
        String(s.resolved_cases),
        String(s.pending_cases),
      ],
    ],
    theme: "grid",
    headStyles: { fillColor: [41, 85, 245] },
    styles: { fontSize: 10, halign: "center" },
  });

  // ---- Top Risk Wards ----
  const wards = risk?.top_risk_wards || dashboard.ward_leaderboard;
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Top Risk Wards", 14, (doc as any).lastAutoTable.finalY + 12);

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 16,
    head: [["Ward", "Complaints", "Open", "Resolved", "Population", "Risk Score", "Level"]],
    body: wards.map((w) => [
      w.ward,
      String(w.complaint_count),
      String(w.open_cases),
      String(w.resolved_cases),
      String(Math.round(w.population)),
      w.risk_score.toFixed(1),
      w.risk_level,
    ]),
    theme: "striped",
    headStyles: { fillColor: [41, 85, 245] },
    styles: { fontSize: 9 },
  });

  // ---- Complaints by Category ----
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Complaints by Category", 14, (doc as any).lastAutoTable.finalY + 12);

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 16,
    head: [["Category", "Count"]],
    body: dashboard.complaints_by_category.map((c) => [c.category, String(c.count)]),
    theme: "striped",
    headStyles: { fillColor: [6, 182, 212] },
    styles: { fontSize: 9 },
  });

  // ---- Footer ----
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      "Generated by CivicLens AI — AI-Powered Community Intelligence Platform",
      14,
      doc.internal.pageSize.getHeight() - 8
    );
  }

  doc.save("CivicLens_Risk_Report.pdf");
}